---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: detector
  namespace: blockade
spec:
  selector:
    matchLabels:
      app: detector
  endpoints:
    - port: metrics
      interval: 30s
